### ISSUE TITLE
launching ArangoDB

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/multinet-docs#9]
With the current instructions, I was not able to launch arango

**Comment by JackWilb** [comment]
Hi Derya, thanks for your first issue 🎉 

Would you mind providing us a bit more info? It's usually best practice to include what you tried (commands), how it failed (error messages, etc.), and, if there is an easy resolution/something you think that should be changed, what should be changed

**Comment by gotdairyya** [comment]
Yes! First I downloaded docker-compose, `pipenv install docker-compose`

Then I tried:
-`derya$ docker-compose up`
ERROR: `docker-compose: command not found`

-derya$ `ARANGO_DATA=~/.local/multinet/arango docker-compose up`
ERROR: `docker-compose: command not found`

**Comment by JackWilb** [comment]
We can definitely be clearer and more verbose when we tell users to install dependencies (I'm thinking links to documentation pages with instructions).

The problem you're having is that the commands `docker` and `docker-compose` are not python packages so cannot be installed with `pip` and, by extension, `pipenv`. To install docker and docker-compose (docker-compose comes with docker on mac) on your mac, you can use [these instructions](https://docs.docker.com/docker-for-mac/install/).

**Comment by gotdairyya** [comment]
I did install docker through the website that you linked to (before I tried to run these commands), but I never ran Docker after installing it

So now that I ran Docker Desktop, it was not initially clear to me if I needed to create a Docker ID (I did not), but I was able to run `docker-compose up`

And I got this error:
```
ERROR: for arangodb  Cannot start service arangodb: Mounts denied: 
The paths /var/arangodb-apps and /var/arangodb
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Comment by JackWilb** [comment]
Okay, I think this should be fixed by running `ARANGO_DATA=~/.local/multinet/arango docker-compose up`

**Comment by JackWilb** [comment]
Woo! Yeah, the second command is the one you have to use on mac for this exact issue. I've got a local branch for some better install instructions that hopefully captures this confusion and helps smooth it out
